"""add search vector

Revision ID: 2bc5270b19a5
Revises: 7fce405d04db
Create Date: 2026-09-21 15:30:44.380069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bc5270b19a5'
down_revision: Union[str, Sequence[str], None] = '7fce405d04db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(company, ''))", persisted=True), nullable=True))
    op.create_index('ix_vacancies_search_vector', 'vacancies', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_search_vector', table_name='vacancies', postgresql_using='gin')
    op.drop_column('vacancies', 'search_vector')
    # ### end Alembic commands ###
